ls:
  # Enforce lowercase letters and digits (flatcase) for directories and files
  # Inspired by Go Style Guide. Read more in this blog post:
  # https://www.mohitkhare.com/blog/go-naming-conventions/
  "{internal,pkg}":
    .go: snake_case # recommendation is flatcase but there are exceptions
    .dir: regex:^[a-z0-9]+$ # flatcase
  cmd:
    .go: snake_case # recommendation is flatcase but there are exceptions
    .dir: kebab-case # cli bin can be kebab-case

ignore:
  - .git
  - "**/.*"
