repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: tools
        name: Install tools
        entry: make install-golangci-lint
        language: system
        pass_filenames: false
        types: [go]
      - id: go-fmt-files
        name: Go formatter (staged files)
        entry: make
        args: [fmt]
        language: system
        pass_filenames: false #
        types: [go]
      - id: autofix-golangci-lint-issues
        name: Autofix golangci-lint linter issues
        entry: bash -c 'make lintfix 2>&1 >/dev/null || true'
        language: system
        pass_filenames: false
        types: [go]
      - id: vet
        name: run go vet
        entry: bash -c 'make vet'
        language: system
        pass_filenames: false
        types: [go]
