name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - uses: pre-commit/action@v3.0.0
