name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - staging
      - prod
      - prod-us-east-1
  push:
    branches:
      - dev
      - staging
      - prod
      - prod-us-east-1

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: go install mvdan.cc/gofumpt@latest
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - uses: pre-commit/action@v3.0.0
